builds:
  - id: tf-preview-gh
    main: ./cmd/tf-preview-gh

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: tf-preview-gh
    builds:
      - tf-preview-gh
    format: binary

release:
  prerelease: auto
